"""Export the static GitHub Pages demo (``docs/``) from the synthetic example notes.

Runs the live pipeline on ``app/examples/synthetic.json`` (written for this demo, no patient
data) and writes ``docs/demo-data.js``, which ``docs/index.html`` renders without any server.

    python app/export_static.py
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

APP = Path(__file__).resolve().parent
sys.path.insert(0, str(APP))
import common as cm  # noqa: E402

cm.prefer_offline_hub()  # before transformers is imported
import inference as inf  # noqa: E402
import render  # noqa: E402
from translate import Translator  # noqa: E402

EXAMPLES = APP / "examples/synthetic.json"
OUT = cm.REPO / "docs/demo-data.js"


def export_one(ex: dict, pipe, translator, en: dict, el: dict) -> dict:
    pairs = translator.en_to_el_pairs(ex["text"]) if ex["language"] == "en" else None
    greek = " ".join(g for _, g in pairs) if pairs else ex["text"]
    res = pipe.predict(greek)
    gold = ex["expected"]
    score = cm.group_score(gold, res.final_codes, pipe.labelset)

    gold_codes = {c for g in gold for c in g}
    rows = [
        {
            "code": c,
            "en": en.get(c, ""),
            "el": el.get(c, ""),
            "status": "correct" if c in gold_codes else "extra",
            "decided_by": cm.MODEL_LABELS[res.source[c]],
            "bert": round(res.bert_scores.get(c, 0.0), 3),
        }
        for c in res.final_codes
    ]
    hit = set(res.final_codes)
    rows += [
        {
            "code": " / ".join(g),
            "en": " / ".join(en.get(c, "") for c in g),
            "el": " / ".join(el.get(c, "") for c in g),
            "status": "missed",
            "decided_by": "",
            "bert": round(max(res.bert_scores.get(c, 0.0) for c in g), 3),
        }
        for g in gold
        if not set(g) & hit
    ]

    spans = render.evidence_spans(res.mentions, res.final_codes)
    colour = render.colours(res.final_codes)
    tips = {c: render.describe(c, en, el) for c in res.final_codes}
    out = {
        "id": ex["id"],
        "language": ex["language"],
        "score": score,
        "n_expected": len(gold),
        "rows": rows,
        "per_model": {cm.MODEL_LABELS[k]: v for k, v in res.per_model.items()},
        "legend_html": render.legend_html(res.final_codes, spans, colour, tips),
        "bert_cut": res.bert_chars is not None,
    }
    if pairs:
        # Locate each translated piece in the cleaned text that was scored, as the app does.
        from preprocessing.cleaning import clean_text

        starts, pos = [], 0
        for _, g in pairs:
            probe = clean_text(g).strip()[:40]
            i = res.text.find(probe, pos)
            if i < 0:
                raise RuntimeError(f"{ex['id']}: could not align the translation with the scored text")
            starts.append(i)
            pos = i + len(probe)
        ends = starts[1:] + [len(res.text)]
        out["pairs"] = [
            {"en": e, "el_html": render.text_html(res.text, spans, colour, tips, start=s, end=t, bert_chars=res.bert_chars)}
            for (e, _), s, t in zip(pairs, starts, ends)
        ]
    else:
        out["text_html"] = render.text_html(res.text, spans, colour, tips, bert_chars=res.bert_chars)
    return out


def main() -> None:
    t = time.time()
    pipe = inf.CardioPipeline()
    translator = Translator()
    en, el = cm.load_english_descriptions(), cm.load_greek_descriptions()
    examples = json.loads(EXAMPLES.read_text(encoding="utf-8"))
    data = []
    for ex in examples:
        d = export_one(ex, pipe, translator, en, el)
        data.append(d)
        print(f"{d['id']}: F1 {d['score']['micro_f1']:.2f}, {len(d['rows'])} rows, BERT window cut: {d['bert_cut']}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps({"generated": time.strftime("%Y-%m-%d"), "examples": data}, ensure_ascii=False)
    OUT.write_text(f"// Generated by app/export_static.py from synthetic notes. Do not edit.\nwindow.DEMO = {payload};\n", encoding="utf-8")
    print(f"wrote {OUT} in {time.time() - t:.0f}s")


if __name__ == "__main__":
    main()
